name: Build and Deploy Hello World service

on:
  push:
    branches:
      - master
env:
  PROJECT_ID: "sprints-lab"
  GKE_CLUSTER: lab
  GKE_ZONE: "us-central1-c"
  GCR_ZONE: "us.gcr.io"
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  IMAGE: hello-world

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: "google-github-actions/auth@v1"
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |-
          gcloud --quiet auth configure-docker

      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      - name: Add short sha env
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV

        # Build the Docker image
      - name: Build
        run: |-
          docker build \
            -f Dockerfile \
            --tag "$GCR_ZONE/$PROJECT_ID/$IMAGE:$SHORT_SHA" \
            --tag "$GCR_ZONE/$PROJECT_ID/$IMAGE:latest" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_HEAD_REF="$GITHUB_HEAD_REF" \
            .

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |-
          docker push "$GCR_ZONE/$PROJECT_ID/$IMAGE:$SHORT_SHA"
          docker push "$GCR_ZONE/$PROJECT_ID/$IMAGE:latest"

      - name: Deploy to dev
        run: |-
          kubectl apply -f ./k8s/ -n dev
